version: '3.8'
services:
  dissertation-backend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8007:8006"
    env_file:
      - .env
    command: ["da-start"]
    networks:
      - app_network
    depends_on:
      - kafka
      - redis

  dissertation-frontend:
    build:
      context: ../frontend 
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - app_network

networks:
  app_network:
    external: true

  