version: '3.8'
services:
  dissertation-backend:
    image: prabhas264/dissertation-backend:ollama
    ports:
      - "8007:8006"
    env_file:
      - .env
    command: ["da-start"]
    networks:
      - app_network
    pull_policy: always

  dissertation-frontend:
    image: prabhas264/dissertation-frontend:1.0.0
    restart: always
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - app_network

networks:
  app_network:
    external: true
