# Define the namespace where Superset will be installed
namespace: superset

# Database configuration
postgresql:
  postgresqlUsername: supersetpostgres
  postgresqlPassword: SuperPGadmin@2024
  postgresqlDatabase: superset

configOverrides: #add secret-key
  secrets: |
    SECRET_KEY = '' 

bootstrapScript: |
  #!/bin/bash
  pip install  psycopg2-binary
